import { RoomState, RoundState, PublicRoomState, PublicRoundState } from './types';
import { getItemById, getRandomItem } from './data/categories';
function nextPlayer(room:RoomState,currentId:string){const connected=room.players.filter(p=>p.connected);const i=connected.findIndex(p=>p.id===currentId);return connected[(i+1+connected.length)%connected.length];}
function chooseFreshItem(room:RoomState,categoryId:string,exclude:string[]=[]){const used=room.usedItemIdsByCategory[categoryId]??[];let item=getRandomItem(categoryId,[...used,...exclude]); if(used.includes(item.id)){room.usedItemIdsByCategory[categoryId]=[];item=getRandomItem(categoryId,exclude);} room.usedItemIdsByCategory[categoryId]=[...(room.usedItemIdsByCategory[categoryId]??[]),item.id];return item;}
export function startNewRound(room:RoomState):RoundState{if(room.players.length<room.settings.playerCount)throw new Error('لم يكتمل عدد اللاعبين');const assignments:any={};const selected:string[]=[];for(const p of room.players){const item=chooseFreshItem(room,room.settings.categoryId,selected);assignments[p.id]=item.id;selected.push(item.id);}const starter=room.players[room.totalRoundsPlayed%room.players.length];const target=room.settings.playerCount===2?room.players.find(p=>p.id!==starter.id)?.id??null:null;const round:RoundState={roundNumber:room.totalRoundsPlayed+1,assignments,currentTurnPlayerId:starter.id,targetPlayerId:target,turnEndsAt:Date.now()+room.settings.turnDurationMs,lastGuessAtByPlayer:{},winnerPlayerId:null,revealed:false,blueActivePlayerId:null,blueExtraTurnsRemaining:0};room.round=round;room.status='playing';return round;}
export function switchTurn(room:RoomState){if(!room.round)return;const r=room.round;const current=r.currentTurnPlayerId;if(r.blueActivePlayerId===current&&r.blueExtraTurnsRemaining>0){r.blueExtraTurnsRemaining--;r.targetPlayerId=room.settings.playerCount===2?room.players.find(p=>p.id!==current)?.id??null:null;r.turnEndsAt=Date.now()+room.settings.turnDurationMs;return;}if(r.blueActivePlayerId===current){r.blueActivePlayerId=null;r.blueExtraTurnsRemaining=0;}const next=nextPlayer(room,current);if(!next)return;r.currentTurnPlayerId=next.id;r.targetPlayerId=room.settings.playerCount===2?room.players.find(p=>p.id!==next.id)?.id??null:null;r.turnEndsAt=Date.now()+room.settings.turnDurationMs;}
export function finishCorrectGuess(room:RoomState,winnerId:string){if(!room.round)return;room.round.winnerPlayerId=winnerId;room.round.revealed=true;room.scores[winnerId]=(room.scores[winnerId]??0)+1;const p=room.players.find(x=>x.id===winnerId);if(p)p.score=room.scores[winnerId];room.totalRoundsPlayed++;const limit=room.settings.roundsMode;if(limit!=='unlimited'&&room.totalRoundsPlayed>=limit){const max=Math.max(...Object.values(room.scores));room.matchWinnerIds=Object.keys(room.scores).filter(id=>room.scores[id]===max);room.status='matchEnd';}else room.status='roundEnd';}
export function checkMatchWinner(room:RoomState){return room.matchWinnerIds[0]??null;}
export function buildPublicRoomState(room:RoomState,forPlayerId:string):PublicRoomState{let publicRound:PublicRoundState|null=null;if(room.round){const r=room.round;let visibleId:string|undefined;if(r.revealed) visibleId=undefined; else if(r.currentTurnPlayerId===forPlayerId) visibleId=r.targetPlayerId??undefined;const visible=visibleId?getItemById(room.settings.categoryId,r.assignments[visibleId])??null:null;publicRound={roundNumber:r.roundNumber,currentTurnPlayerId:r.currentTurnPlayerId,targetPlayerId:r.targetPlayerId,turnEndsAt:r.turnEndsAt,winnerPlayerId:r.winnerPlayerId,revealed:r.revealed,opponentItemForMe:visible,blueActivePlayerId:r.blueActivePlayerId,blueTurnsLeftIncludingCurrent:r.blueActivePlayerId===r.currentTurnPlayerId?r.blueExtraTurnsRemaining+1:0};if(r.revealed){const revealedItems:any={};for(const p of room.players){const item=getItemById(room.settings.categoryId,r.assignments[p.id]);if(item)revealedItems[p.id]=item;}publicRound.revealedItems=revealedItems;}}
return{code:room.code,status:room.status,players:room.players.map(({socketId,token,...p})=>p),settings:room.settings,scores:room.scores,round:publicRound,cardState:room.cardState,totalRoundsPlayed:room.totalRoundsPlayed,matchWinnerIds:room.matchWinnerIds};}
