import { Server, Socket } from 'socket.io';
import { createRoom,getRoom,joinRoom,findRoomBySocketId,removePlayerFromRoom,markPlayerConnection } from './roomManager';
import { startNewRound,switchTurn,finishCorrectGuess,buildPublicRoomState } from './gameLogic';
import { ALL_CATEGORIES,getCategoryById,getRandomItem } from './data/categories';
import { RoomState,RoundsMode,PlayerCount } from './types';
const turnTimeouts=new Map<string,NodeJS.Timeout>();
const disconnectGraceTimeouts=new Map<string,NodeJS.Timeout>();
const RECONNECT_GRACE_MS=5*60*1000;
function clearTurnTimer(code:string){const t=turnTimeouts.get(code);if(t){clearTimeout(t);turnTimeouts.delete(code);}}
function broadcastRoomState(io:Server,room:RoomState){for(const p of room.players){if(p.connected)io.to(p.socketId).emit('room:state',buildPublicRoomState(room,p.id));}}
function scheduleTurnTimeout(io:Server,room:RoomState){clearTurnTimer(room.code);if(!room.round||room.status!=='playing')return;const delay=Math.max(0,room.round.turnEndsAt-Date.now());const t=setTimeout(()=>{const current=getRoom(room.code);if(!current||!current.round||current.status!=='playing')return;const previous=current.round.currentTurnPlayerId;switchTurn(current);io.to(current.code).emit('turn:timeout',{previousPlayerId:previous});broadcastRoomState(io,current);scheduleTurnTimeout(io,current);},delay);turnTimeouts.set(room.code,t);}
function playerBySocket(room:RoomState,socket:Socket){return room.players.find(p=>p.socketId===socket.id);}
export function registerSocketHandlers(io:Server,socket:Socket){
 socket.on('categories:list',(cb:any)=>cb(ALL_CATEGORIES.map(c=>({...c,items:[]}))));
 socket.on('room:create',(payload:{playerName?:string;playerToken?:string;playerCount?:PlayerCount;roundsMode?:RoundsMode},cb:any)=>{try{const name=String(payload.playerName??'').trim().slice(0,20);const token=String(payload.playerToken??'').trim();const count=[2,3,4].includes(Number(payload.playerCount))?Number(payload.playerCount) as PlayerCount:2;const mode=payload.roundsMode==='unlimited'||payload.roundsMode===30||payload.roundsMode===45?payload.roundsMode:'unlimited';if(!name||!token)return cb({ok:false,error:'تعذر تحديد اللاعب'});const room=createRoom(socket.id,name,token,count,mode);socket.join(room.code);cb({ok:true,room:buildPublicRoomState(room,token)});}catch(e){cb({ok:false,error:e instanceof Error?e.message:'تعذر إنشاء الغرفة'});}});
 socket.on('room:join',(payload:{code?:string;playerName?:string;playerToken?:string},cb:any)=>{const code=String(payload.code??'').trim().toUpperCase();const name=String(payload.playerName??'').trim().slice(0,20);const token=String(payload.playerToken??'').trim();if(!code||!name||!token)return cb({ok:false,error:'أكمل البيانات'});const result=joinRoom(code,socket.id,name,token);if(!result.room)return cb({ok:false,error:result.error});socket.join(result.room.code);const oldTimer=disconnectGraceTimeouts.get(token);if(oldTimer){clearTimeout(oldTimer);disconnectGraceTimeouts.delete(token);}cb({ok:true,room:buildPublicRoomState(result.room,token),reconnected:result.reconnected});broadcastRoomState(io,result.room);});
 socket.on('room:updateSettings',(payload:{code:string;categoryId?:string;turnDurationMs?:number;roundsMode?:RoundsMode},cb:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(!room||!actor)return cb({ok:false,error:'الغرفة غير موجودة'});if(room.hostId!==actor.id)return cb({ok:false,error:'المضيف فقط يستطيع التعديل'});if(room.status!=='lobby'&&room.status!=='settings')return cb({ok:false,error:'لا يمكن تعديل الإعدادات أثناء الجولة'});if(payload.categoryId&&getCategoryById(payload.categoryId))room.settings.categoryId=payload.categoryId;if(payload.turnDurationMs&&payload.turnDurationMs>=15000)room.settings.turnDurationMs=payload.turnDurationMs;if(room.totalRoundsPlayed===0&&(payload.roundsMode==='unlimited'||payload.roundsMode===30||payload.roundsMode===45))room.settings.roundsMode=payload.roundsMode;room.players.forEach(p=>p.isReady=false);cb({ok:true});broadcastRoomState(io,room);});
 socket.on('room:setReady',(payload:{code:string;ready:boolean},cb?:any)=>{const room=getRoom(payload.code);const p=room?playerBySocket(room,socket):undefined;if(!room||!p)return cb?.({ok:false,error:'أنت لست داخل الغرفة'});p.isReady=payload.ready;cb?.({ok:true});const allReady=room.players.length===room.settings.playerCount&&room.players.every(x=>x.isReady&&x.connected);if(allReady&&room.status!=='playing'){startNewRound(room);broadcastRoomState(io,room);scheduleTurnTimeout(io,room);return;}broadcastRoomState(io,room);});
 socket.on('turn:selectTarget',(payload:{code:string;targetPlayerId:string},cb?:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(!room||!room.round||!actor||room.status!=='playing')return cb?.({ok:false,error:'لا توجد جولة نشطة'});if(room.round.currentTurnPlayerId!==actor.id)return cb?.({ok:false,error:'ليس دورك'});if(actor.id===payload.targetPlayerId||!room.players.some(p=>p.id===payload.targetPlayerId))return cb?.({ok:false,error:'اختر لاعبًا آخر'});room.round.targetPlayerId=payload.targetPlayerId;cb?.({ok:true});broadcastRoomState(io,room);});
 socket.on('answer:judge',(payload:{code:string;correct:boolean},cb?:any)=>{const room=getRoom(payload.code);const judge=room?playerBySocket(room,socket):undefined;if(!room||!room.round||!judge||room.status!=='playing')return cb?.({ok:false,error:'لا توجد جولة نشطة'});if(room.round.targetPlayerId!==judge.id)return cb?.({ok:false,error:'اللاعب المستهدف فقط يقيّم الإجابة'});const currentId=room.round.currentTurnPlayerId;const current=room.players.find(p=>p.id===currentId);if(payload.correct){clearTurnTimer(room.code);finishCorrectGuess(room,currentId);io.to(room.code).emit('answer:judged',{correct:true,guessedPlayerId:currentId,guessedPlayerName:current?.name});}else{switchTurn(room);io.to(room.code).emit('answer:judged',{correct:false,guessedPlayerId:currentId,guessedPlayerName:current?.name});scheduleTurnTimeout(io,room);}cb?.({ok:true});broadcastRoomState(io,room);});
 socket.on('card:changeOpponent',(payload:{code:string;targetPlayerId?:string},cb?:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(!room||!room.round||!actor||room.status!=='playing')return cb?.({ok:false,error:'يمكن استخدام البطاقة أثناء اللعب فقط'});const targetId=payload.targetPlayerId||room.round.targetPlayerId;if(!targetId||targetId===actor.id)return cb?.({ok:false,error:'اختر لاعبًا'});const cards=room.cardState[actor.id];if(!cards?.redAvailable)return cb?.({ok:false,error:'تم استخدام البطاقة سابقًا'});const current=room.round.assignments[targetId];const replacement=getRandomItem(room.settings.categoryId,[current,...Object.values(room.round.assignments)]);room.round.assignments[targetId]=replacement.id;cards.redAvailable=false;io.to(room.code).emit('card:used',{type:'red',playerId:actor.id,playerName:actor.name});cb?.({ok:true});broadcastRoomState(io,room);});
 socket.on('card:tripleTurn',(payload:{code:string},cb?:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(!room||!room.round||!actor||room.status!=='playing')return cb?.({ok:false});if(room.round.currentTurnPlayerId!==actor.id)return cb?.({ok:false,error:'استخدمها أثناء دورك'});const cards=room.cardState[actor.id];if(!cards?.blueAvailable)return cb?.({ok:false,error:'تم استخدام البطاقة'});cards.blueAvailable=false;room.round.blueActivePlayerId=actor.id;room.round.blueExtraTurnsRemaining=2;cb?.({ok:true});broadcastRoomState(io,room);});
 socket.on('round:next',(payload:{code:string},cb?:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(!room||!actor)return cb?.({ok:false});if(room.hostId!==actor.id)return cb?.({ok:false,error:'المضيف فقط يبدأ الجولة التالية'});if(room.status!=='roundEnd')return cb?.({ok:false,error:'الجولة لم تنته بعد'});room.round=null;room.status='settings';room.players.forEach(p=>p.isReady=false);cb?.({ok:true});broadcastRoomState(io,room);});
 socket.on('room:leave',(payload:{code:string},cb?:any)=>{const room=getRoom(payload.code);const actor=room?playerBySocket(room,socket):undefined;if(room&&actor){removePlayerFromRoom(room.code,actor.id);socket.leave(room.code);clearTurnTimer(room.code);const rest=getRoom(room.code);if(rest){rest.status='lobby';rest.round=null;rest.players.forEach(p=>p.isReady=false);broadcastRoomState(io,rest);}}cb?.({ok:true});});
 socket.on('disconnect',()=>{const room=findRoomBySocketId(socket.id);if(!room)return;const p=playerBySocket(room,socket);if(!p)return;markPlayerConnection(room.code,socket.id,false);broadcastRoomState(io,room);const token=p.token;const t=setTimeout(()=>{const r=getRoom(room.code);const current=r?.players.find(x=>x.token===token);if(r&&current&&!current.connected){removePlayerFromRoom(r.code,current.id);broadcastRoomState(io,r);}disconnectGraceTimeouts.delete(token);},RECONNECT_GRACE_MS);disconnectGraceTimeouts.set(token,t);});
}
